"""PDF report generation for the DX diagnostic assessment."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from io import BytesIO
from typing import Any

from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.shapes import Drawing, Line, Rect, String
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
	Image,
	KeepInFrame,
	ListFlowable,
	ListItem,
	PageBreak,
	Paragraph,
	SimpleDocTemplate,
	Spacer,
	Table,
	TableStyle,
)

from agent.llm_analyzer import FullAnalysis
from agent.meti_framework import DIMENSIONS, Dimension, get_text
from agent.scoring_engine import ScoringResult


@dataclass(frozen=True)
class _RoadmapAction:
	"""Internal representation for roadmap rows."""

	action: str
	dimension: str
	expected_impact: str
	timeline: str
	priority: float


class PDFGenerator:
	"""Generate the DX maturity diagnostic report as a PDF document."""

	def __init__(self, language: str):
		"""Initialize the generator for a selected output language."""

		normalized = language.strip().lower()
		self.language = normalized if normalized in {"en", "pt", "ja"} else "en"
		if self.language == "ja":
			from reportlab.pdfbase import pdfmetrics
			from reportlab.pdfbase.cidfonts import UnicodeCIDFont

			try:
				pdfmetrics.registerFont(UnicodeCIDFont("HeiseiKakuGo-W5"))
			except Exception:
				self.language = "en"
		self.styles = self._build_styles()
		self.translations = self._build_translations()
		self._font_name = "HeiseiKakuGo-W5" if self.language == "ja" else "Helvetica"

	def _build_styles(self) -> dict[str, ParagraphStyle]:
		"""Build the paragraph styles used throughout the report."""

		sample = getSampleStyleSheet()
		base_font = "Helvetica"
		japanese_font = "HeiseiKakuGo-W5"
		font_name = japanese_font if self.language == "ja" else base_font

		styles = {
			"title": ParagraphStyle(
				"DXTitle",
				parent=sample["Title"],
				fontName=font_name,
				fontSize=24,
				leading=28,
				textColor=colors.HexColor("#163A63"),
				alignment=TA_CENTER,
				spaceAfter=12,
			),
			"subtitle": ParagraphStyle(
				"DXSubtitle",
				parent=sample["BodyText"],
				fontName=font_name,
				fontSize=12,
				leading=15,
				alignment=TA_CENTER,
				textColor=colors.HexColor("#4A4A4A"),
			),
			"heading": ParagraphStyle(
				"DXHeading",
				parent=sample["Heading1"],
				fontName=font_name,
				fontSize=18,
				leading=22,
				textColor=colors.HexColor("#163A63"),
				spaceAfter=10,
			),
			"subheading": ParagraphStyle(
				"DXSubheading",
				parent=sample["Heading2"],
				fontName=font_name,
				fontSize=13,
				leading=16,
				textColor=colors.HexColor("#163A63"),
				spaceAfter=6,
			),
			"body": ParagraphStyle(
				"DXBody",
				parent=sample["BodyText"],
				fontName=font_name,
				fontSize=9.5,
				leading=12,
				textColor=colors.HexColor("#222222"),
			),
			"body_small": ParagraphStyle(
				"DXBodySmall",
				parent=sample["BodyText"],
				fontName=font_name,
				fontSize=8.5,
				leading=10.5,
				textColor=colors.HexColor("#222222"),
			),
			"table_header": ParagraphStyle(
				"DXTableHeader",
				parent=sample["BodyText"],
				fontName=font_name,
				fontSize=9,
				leading=11,
				alignment=TA_CENTER,
				textColor=colors.white,
			),
			"table_body": ParagraphStyle(
				"DXTableBody",
				parent=sample["BodyText"],
				fontName=font_name,
				fontSize=8.5,
				leading=10,
				textColor=colors.black,
			),
			"maturity_label": ParagraphStyle(
				"DXMaturityLabel",
				parent=sample["BodyText"],
				fontName=font_name,
				fontSize=16,
				leading=18,
				alignment=TA_CENTER,
				textColor=colors.white,
			),
			"badge_text": ParagraphStyle(
				"DXBadgeText",
				parent=sample["BodyText"],
				fontName=font_name,
				fontSize=14,
				leading=16,
				alignment=TA_CENTER,
				textColor=colors.white,
			),
		}
		return styles

	def _build_translations(self) -> dict[str, dict[str, str]]:
		"""Build static localized strings for the report sections."""

		return {
			"en": {
				"report_title": "Digital Transformation Maturity Diagnostic Report",
				"subtitle": "Academic diagnostic report for SME digital transformation maturity",
				"based_on": "Based on: METI DX Promotion Index (経済産業省, 2019)",
				"generated_by": "Generated by shinkyou_agent (診鏡 Shinkyō Agent) — Academic Portfolio Project",
				"generated_on": "Date generated",
				"executive_summary": "Executive Summary",
				"overall_level": "Overall Maturity Level",
				"score_table": "Score Table",
				"dimension": "Dimension",
				"score": "Score",
				"weight": "Weight",
				"weighted": "Weighted",
				"your_company": "Your Company",
				"sme_average": "SME Average (METI 2022)",
				"benchmark_comparison": "Benchmark Comparison",
				"interpretation": "Interpretation",
				"roadmap": "90-Day Action Roadmap",
				"methodology": "Methodology",
				"framework_desc": "METI DX Promotion Index is Japan's official self-assessment framework for DX readiness.",
				"scoring_method": "Composite scores combine Likert responses and LLM qualitative assessment using a 60/40 weighting.",
				"disclaimer": "This report is generated by an AI agent for academic research purposes",
				"citation": "METI (2019) DX推進指標とそのガイダンス",
				"top_actions": "Top 5 Priority Actions",
				"action": "Action",
				"expected_impact": "Expected Impact",
				"timeline": "Timeline",
				"justification": "LLM Justification",
				"gaps": "Gaps",
				"recommendations": "Recommendations",
				"company_context": "Company Context",
				"legend_your_company": "Your Company",
				"legend_sme_average": "SME Average (METI 2022)",
			},
			"pt": {
				"report_title": "Relatório de Diagnóstico de Maturidade em Transformação Digital",
				"subtitle": "Relatório acadêmico de diagnóstico da maturidade em transformação digital para PMEs",
				"based_on": "Baseado em: METI DX Promotion Index (経済産業省, 2019)",
				"generated_by": "Generated by shinkyou_agent (診鏡 Shinkyō Agent) — Academic Portfolio Project",
				"generated_on": "Data de geração",
				"executive_summary": "Resumo Executivo",
				"overall_level": "Nível Geral de Maturidade",
				"score_table": "Tabela de Pontuação",
				"dimension": "Dimensão",
				"score": "Pontuação",
				"weight": "Peso",
				"weighted": "Ponderado",
				"your_company": "Sua Empresa",
				"sme_average": "Média das PMEs (METI 2022)",
				"benchmark_comparison": "Comparação com Referência",
				"interpretation": "Interpretação",
				"roadmap": "Roteiro de Ação em 90 Dias",
				"methodology": "Metodologia",
				"framework_desc": "O METI DX Promotion Index é o framework oficial de autoavaliação do Japão para prontidão em DX.",
				"scoring_method": "As pontuações compostas combinam respostas Likert e a avaliação qualitativa do LLM com peso 60/40.",
				"disclaimer": "Este relatório é gerado por um agente de IA para fins de pesquisa acadêmica",
				"citation": "METI (2019) DX推進指標とそのガイダンス",
				"top_actions": "5 Ações Prioritárias",
				"action": "Ação",
				"expected_impact": "Impacto Esperado",
				"timeline": "Prazo",
				"justification": "Justificativa do LLM",
				"gaps": "Lacunas",
				"recommendations": "Recomendações",
				"company_context": "Contexto da Empresa",
				"legend_your_company": "Sua Empresa",
				"legend_sme_average": "Média das PMEs (METI 2022)",
			},
			"ja": {
				"report_title": "デジタル変革成熟度診断レポート",
				"subtitle": "中小企業のデジタル変革成熟度に関する学術診断レポート",
				"based_on": "Based on: METI DX Promotion Index (経済産業省, 2019)",
				"generated_by": "Generated by shinkyou_agent (診鏡 Shinkyō Agent) — Academic Portfolio Project",
				"generated_on": "作成日",
				"executive_summary": "エグゼクティブサマリー",
				"overall_level": "総合成熟度レベル",
				"score_table": "スコア表",
				"dimension": "観点",
				"score": "スコア",
				"weight": "重み",
				"weighted": "加重値",
				"your_company": "自社",
				"sme_average": "中小企業平均（METI 2022）",
				"benchmark_comparison": "ベンチマーク比較",
				"interpretation": "解釈",
				"roadmap": "90日アクションロードマップ",
				"methodology": "方法論",
				"framework_desc": "METI DX推進指標は、DX実現度を評価する日本の公式自己診断フレームワークです。",
				"scoring_method": "総合スコアは、Likert評価とLLMの定性的評価を60/40で統合しています。",
				"disclaimer": "This report is generated by an AI agent for academic research purposes",
				"citation": "METI (2019) DX推進指標とそのガイダンス",
				"top_actions": "優先アクション上位5件",
				"action": "アクション",
				"expected_impact": "期待効果",
				"timeline": "実施時期",
				"justification": "LLMによる説明",
				"gaps": "ギャップ",
				"recommendations": "改善提案",
				"company_context": "企業情報",
				"legend_your_company": "自社",
				"legend_sme_average": "中小企業平均（METI 2022）",
			},
		}

	def _t(self, key: str) -> str:
		"""Return a localized string for the current report language."""

		return self.translations[self.language][key]

	def _page_footer(self, canvas: Any, doc: Any) -> None:
		"""Draw the footer on each page."""

		canvas.saveState()
		canvas.setStrokeColor(colors.HexColor("#D0D0D0"))
		canvas.line(doc.leftMargin, 34, doc.pagesize[0] - doc.rightMargin, 34)
		canvas.setFont("Helvetica", 8)
		canvas.setFillColor(colors.HexColor("#6B6B6B"))
		canvas.drawCentredString(
			doc.pagesize[0] / 2,
			22,
			self._t("generated_by"),
		)
		canvas.restoreState()

	def _company_name(self, company_profile: dict) -> str:
		"""Return a display name for the company."""

		company_name = company_profile.get("company_name")
		if isinstance(company_name, str) and company_name.strip():
			return company_name.strip()
		return self._t("your_company")

	def _format_percent(self, value: float) -> str:
		"""Format a numeric value as a score with one decimal place."""

		return f"{value:.2f}"

	def _maturity_badge_color(self, level: int) -> colors.Color:
		"""Return the badge color for a maturity level."""

		if level <= 1:
			return colors.HexColor("#C0392B")
		if level == 2:
			return colors.HexColor("#E67E22")
		if level == 3:
			return colors.HexColor("#F1C40F")
		return colors.HexColor("#2E8B57")

	def _dimension_analysis_map(self, llm_analysis: FullAnalysis) -> dict[int, dict[str, Any]]:
		"""Map dimension identifiers to analysis payloads."""

		return {analysis["dimension_id"]: analysis for analysis in llm_analysis["dimensions"]}

	def _dimension_score_map(self, scoring_result: ScoringResult) -> dict[int, dict[str, Any]]:
		"""Map dimension identifiers to scoring payloads."""

		return {item["dimension_id"]: item for item in scoring_result["dimension_scores"]}

	def _benchmark_score(self, scoring_result: ScoringResult, dimension_id: int) -> float:
		"""Reconstruct the benchmark average from the score gap and company score."""

		score_map = self._dimension_score_map(scoring_result)
		score_item = score_map.get(dimension_id)
		if score_item is None:
			return 0.0
		return float(score_item["composite_score"]) + float(scoring_result["benchmark_gaps"].get(dimension_id, 0.0))

	def _build_cover_story(self, company_profile: dict) -> list[Any]:
		"""Build the cover page content."""

		story: list[Any] = []
		story.append(Spacer(1, 0.65 * inch))
		story.append(Paragraph(self._t("report_title"), self.styles["title"]))
		story.append(Spacer(1, 0.12 * inch))
		story.append(Paragraph(self._t("subtitle"), self.styles["subtitle"]))
		story.append(Spacer(1, 0.8 * inch))
		story.append(Paragraph(self._company_name(company_profile), self.styles["heading"]))
		story.append(Spacer(1, 0.12 * inch))
		story.append(
			Paragraph(
				f"{self._t('generated_on')}: {datetime.now().strftime('%Y-%m-%d')}",
				self.styles["body"],
			)
		)
		story.append(Spacer(1, 0.12 * inch))
		story.append(Paragraph(self._t("based_on"), self.styles["body"]))
		story.append(Spacer(1, 0.8 * inch))
		story.append(Paragraph(self._t("generated_by"), self.styles["subtitle"]))
		return story

	def _build_maturity_badge(self, scoring_result: ScoringResult) -> Table:
		"""Build the maturity level badge for the executive summary page."""

		level = scoring_result["maturity_level"]
		badge_text = Paragraph(
			f"Level {level} | {scoring_result['maturity_label_en']} | {scoring_result['maturity_label_pt']} | {scoring_result['maturity_label_ja']}",
			self.styles["badge_text"],
		)
		table = Table([[badge_text]], colWidths=[5.7 * inch])
		table.setStyle(
			TableStyle(
				[
					("BACKGROUND", (0, 0), (-1, -1), self._maturity_badge_color(level)),
					("BOX", (0, 0), (-1, -1), 1, colors.white),
					("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
					("ALIGN", (0, 0), (-1, -1), "CENTER"),
					("TOPPADDING", (0, 0), (-1, -1), 10),
					("BOTTOMPADDING", (0, 0), (-1, -1), 10),
					("LEFTPADDING", (0, 0), (-1, -1), 10),
					("RIGHTPADDING", (0, 0), (-1, -1), 10),
				]
			)
		)
		return table

	def _build_score_table(self, scoring_result: ScoringResult) -> Table:
		"""Build the score summary table for the executive summary page."""

		score_map = self._dimension_score_map(scoring_result)
		header = [
			Paragraph(self._t("dimension"), self.styles["table_header"]),
			Paragraph(self._t("score"), self.styles["table_header"]),
			Paragraph(self._t("weight"), self.styles["table_header"]),
			Paragraph(self._t("weighted"), self.styles["table_header"]),
		]

		rows = [header]
		for dimension in DIMENSIONS:
			item = score_map[dimension.id]
			rows.append(
				[
					Paragraph(get_text(dimension, self.language), self.styles["table_body"]),
					Paragraph(self._format_percent(item["composite_score"]), self.styles["table_body"]),
					Paragraph(f"{item['weight']:.2f}", self.styles["table_body"]),
					Paragraph(self._format_percent(item["weighted_contribution"]), self.styles["table_body"]),
				]
			)

		table = Table(rows, colWidths=[2.55 * inch, 0.8 * inch, 0.75 * inch, 0.95 * inch], repeatRows=1)
		table.setStyle(
			TableStyle(
				[
					("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#163A63")),
					("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
					("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D0D0D0")),
					("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.HexColor("#F8F8F8")]),
					("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
					("LEFTPADDING", (0, 0), (-1, -1), 4),
					("RIGHTPADDING", (0, 0), (-1, -1), 4),
					("TOPPADDING", (0, 0), (-1, -1), 4),
					("BOTTOMPADDING", (0, 0), (-1, -1), 4),
				]
			)
		)
		return table

	def _build_radar_image(self, radar_chart_bytes: bytes) -> Image:
		"""Convert radar chart bytes into a ReportLab image."""

		image = Image(BytesIO(radar_chart_bytes))
		image.drawWidth = 3.7 * inch
		image.drawHeight = 3.7 * inch
		return image

	def _build_dimension_score_bar(self, score: float, width: float = 5.8 * inch) -> Drawing:
		"""Build a proportional score bar for one dimension."""

		height = 18
		drawing = Drawing(width, height)
		drawing.add(Rect(0, 0, width, height, fillColor=colors.HexColor("#ECEFF3"), strokeColor=colors.HexColor("#D0D0D0")))
		filled_width = max(0.0, min(width, (score / 4.0) * width))
		drawing.add(Rect(0, 0, filled_width, height, fillColor=colors.HexColor("#1F77B4"), strokeColor=None))
		drawing.add(String(width + 2, 2, f"{score:.2f}/4.00", fontName="Helvetica", fontSize=9, fillColor=colors.HexColor("#444444")))
		return drawing

	def _build_bullet_list(self, items: list[str], style: ParagraphStyle, bullet_type: str = "bullet") -> ListFlowable:
		"""Build a bullet or numbered list from text items."""

		flowables = [ListItem(Paragraph(item, style), leftIndent=8) for item in items if item.strip()]
		return ListFlowable(
			flowables,
			bulletType=bullet_type,
			start="1",
			leftIndent=14,
			bulletFontName=self._font_name,
			bulletFontSize=9,
		)

	def _build_dimension_story(
		self,
		dimension: Dimension,
		scoring_result: ScoringResult,
		llm_analysis: FullAnalysis,
	) -> list[Any]:
		"""Build the content for a single dimension page."""

		score_map = self._dimension_score_map(scoring_result)
		analysis_map = self._dimension_analysis_map(llm_analysis)
		score_item = score_map[dimension.id]
		analysis_item = analysis_map[dimension.id]

		icon_map = {1: "◆", 2: "■", 3: "▲", 4: "●", 5: "✦"}
		header = Paragraph(
			f"{icon_map.get(dimension.id, '•')} {get_text(dimension, self.language)}",
			self.styles["heading"],
		)

		justification = analysis_item["justification"].strip()
		gap_items = analysis_item["gaps"][:3]
		recommendation_items = analysis_item["recommendations"][:3]

		story: list[Any] = [header, Spacer(1, 0.08 * inch)]
		story.append(Paragraph(self._t("score"), self.styles["subheading"]))
		story.append(self._build_dimension_score_bar(score_item["composite_score"]))
		story.append(Spacer(1, 0.12 * inch))
		story.append(Paragraph(self._t("justification"), self.styles["subheading"]))
		story.append(Paragraph(justification, self.styles["body_small"]))
		story.append(Spacer(1, 0.08 * inch))
		story.append(Paragraph(self._t("gaps"), self.styles["subheading"]))
		story.append(self._build_bullet_list(gap_items or ["-"], self.styles["body_small"], bullet_type="bullet"))
		story.append(Spacer(1, 0.08 * inch))
		story.append(Paragraph(self._t("recommendations"), self.styles["subheading"]))
		story.append(self._build_bullet_list(recommendation_items or ["-"], self.styles["body_small"], bullet_type="1"))
		return story

	def _build_benchmark_drawing(self, scoring_result: ScoringResult) -> Drawing:
		"""Build the comparison bar chart for the benchmark page."""

		score_map = self._dimension_score_map(scoring_result)
		company_values = [score_map[dimension.id]["composite_score"] for dimension in DIMENSIONS]
		benchmark_values = [self._benchmark_score(scoring_result, dimension.id) for dimension in DIMENSIONS]
		labels = [get_text(dimension, self.language) for dimension in DIMENSIONS]

		drawing = Drawing(500, 240)
		chart = VerticalBarChart()
		chart.x = 40
		chart.y = 40
		chart.height = 150
		chart.width = 390
		chart.data = [company_values, benchmark_values]
		chart.categoryAxis.categoryNames = labels
		chart.categoryAxis.labels.boxAnchor = "ne"
		chart.categoryAxis.labels.angle = 25
		chart.categoryAxis.labels.fontName = self._font_name
		chart.categoryAxis.labels.fontSize = 7.5
		chart.valueAxis.valueMin = 0
		chart.valueAxis.valueMax = 4
		chart.valueAxis.valueStep = 1
		chart.valueAxis.labels.fontName = "Helvetica"
		chart.valueAxis.labels.fontSize = 8
		chart.bars[0].fillColor = colors.HexColor("#1F77B4")
		chart.bars[1].fillColor = colors.HexColor("#FF7F0E")
		chart.barLabelFormat = "%.2f"
		chart.barLabels.fontName = "Helvetica"
		chart.barLabels.fontSize = 7
		drawing.add(chart)

		drawing.add(Rect(25, 210, 10, 10, fillColor=colors.HexColor("#1F77B4"), strokeColor=None))
		drawing.add(String(40, 210, self._t("legend_your_company"), fontName=self._font_name, fontSize=9))
		drawing.add(Rect(170, 210, 10, 10, fillColor=colors.HexColor("#FF7F0E"), strokeColor=None))
		drawing.add(String(185, 210, self._t("legend_sme_average"), fontName=self._font_name, fontSize=9))
		return drawing

	def _benchmark_interpretation(self, scoring_result: ScoringResult) -> str:
		"""Return a short benchmark interpretation paragraph."""

		score_map = self._dimension_score_map(scoring_result)
		gaps = scoring_result["benchmark_gaps"]
		sorted_dimensions = sorted(DIMENSIONS, key=lambda dimension: gaps.get(dimension.id, 0.0), reverse=True)
		highest_gap_dimension = sorted_dimensions[0]
		lowest_gap_dimension = sorted_dimensions[-1]

		if self.language == "pt":
			return (
				f"A maior lacuna aparece em {get_text(highest_gap_dimension, self.language)}, sugerindo priorização de melhorias estruturais. "
				f"A melhor proximidade com a referência está em {get_text(lowest_gap_dimension, self.language)}."
			)
		if self.language == "ja":
			return (
				f"最も大きいギャップは「{get_text(highest_gap_dimension, self.language)}」であり、構造的な改善を優先する必要があります。 "
				f"ベンチマークへの最も近い観点は「{get_text(lowest_gap_dimension, self.language)}」です。"
			)
		return (
			f"The largest gap appears in {get_text(highest_gap_dimension, self.language)}, indicating a clear priority for structural improvement. "
			f"The closest area to the benchmark is {get_text(lowest_gap_dimension, self.language)}."
		)

	def _collect_priority_actions(self, scoring_result: ScoringResult, llm_analysis: FullAnalysis) -> list[_RoadmapAction]:
		"""Collect the top priority actions from all recommendation lists."""

		analysis_map = self._dimension_analysis_map(llm_analysis)
		gaps = scoring_result["benchmark_gaps"]
		candidates: list[_RoadmapAction] = []
		seen: set[str] = set()

		for dimension in sorted(DIMENSIONS, key=lambda item: gaps.get(item.id, 0.0), reverse=True):
			analysis = analysis_map.get(dimension.id)
			if analysis is None:
				continue
			recommendations = analysis.get("recommendations", [])[:3]
			for index, recommendation in enumerate(recommendations):
				recommendation_text = recommendation.strip()
				normalized = recommendation_text.lower()
				if not recommendation_text or normalized in seen:
					continue
				seen.add(normalized)
				gap = float(gaps.get(dimension.id, 0.0))
				if gap >= 0.8:
					impact = {"en": "High", "pt": "Alto", "ja": "高"}[self.language]
				elif gap >= 0.4:
					impact = {"en": "Moderate", "pt": "Moderado", "ja": "中"}[self.language]
				else:
					impact = {"en": "Quick win", "pt": "Ganho rápido", "ja": "短期成果"}[self.language]

				if len(candidates) == 0:
					timeline = {"en": "Days 1-15", "pt": "Dias 1-15", "ja": "1〜15日"}[self.language]
				elif len(candidates) == 1:
					timeline = {"en": "Days 16-30", "pt": "Dias 16-30", "ja": "16〜30日"}[self.language]
				elif len(candidates) == 2:
					timeline = {"en": "Days 31-45", "pt": "Dias 31-45", "ja": "31〜45日"}[self.language]
				elif len(candidates) == 3:
					timeline = {"en": "Days 46-60", "pt": "Dias 46-60", "ja": "46〜60日"}[self.language]
				else:
					timeline = {"en": "Days 61-90", "pt": "Dias 61-90", "ja": "61〜90日"}[self.language]

				candidates.append(
					_RoadmapAction(
						action=recommendation_text,
						dimension=get_text(dimension, self.language),
						expected_impact=impact,
						timeline=timeline,
						priority=gap + (0.1 * (3 - index)),
					)
				)
				if len(candidates) >= 5:
					return candidates

		while len(candidates) < 5:
			filler_index = len(candidates) % len(DIMENSIONS)
			dimension = DIMENSIONS[filler_index]
			fallback_text = {
				"en": "Establish a measurable improvement cycle and assign ownership.",
				"pt": "Estabeleça um ciclo de melhoria mensurável e atribua responsabilidade.",
				"ja": "測定可能な改善サイクルを設定し、責任者を明確にしてください。",
			}[self.language]
			candidates.append(
				_RoadmapAction(
					action=fallback_text,
					dimension=get_text(dimension, self.language),
					expected_impact={"en": "Moderate", "pt": "Moderado", "ja": "中"}[self.language],
					timeline={"en": "Days 61-90", "pt": "Dias 61-90", "ja": "61〜90日"}[self.language],
					priority=0.0,
				)
			)

		return candidates[:5]

	def _build_roadmap_table(self, scoring_result: ScoringResult, llm_analysis: FullAnalysis) -> Table:
		"""Build the 90-day action roadmap table."""

		actions = self._collect_priority_actions(scoring_result, llm_analysis)
		header = [
			Paragraph(self._t("action"), self.styles["table_header"]),
			Paragraph(self._t("dimension"), self.styles["table_header"]),
			Paragraph(self._t("expected_impact"), self.styles["table_header"]),
			Paragraph(self._t("timeline"), self.styles["table_header"]),
		]
		rows = [header]
		for action in actions:
			rows.append(
				[
					Paragraph(action.action, self.styles["table_body"]),
					Paragraph(action.dimension, self.styles["table_body"]),
					Paragraph(action.expected_impact, self.styles["table_body"]),
					Paragraph(action.timeline, self.styles["table_body"]),
				]
			)

		table = Table(rows, colWidths=[2.85 * inch, 1.35 * inch, 1.0 * inch, 0.9 * inch], repeatRows=1)
		table.setStyle(
			TableStyle(
				[
					("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#163A63")),
					("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
					("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D0D0D0")),
					("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.HexColor("#F8F8F8")]),
					("VALIGN", (0, 0), (-1, -1), "TOP"),
					("LEFTPADDING", (0, 0), (-1, -1), 4),
					("RIGHTPADDING", (0, 0), (-1, -1), 4),
					("TOPPADDING", (0, 0), (-1, -1), 4),
					("BOTTOMPADDING", (0, 0), (-1, -1), 4),
				]
			)
		)
		return table

	def _build_methodology_story(self) -> list[Any]:
		"""Build the methodology page content."""

		story: list[Any] = [Paragraph(self._t("methodology"), self.styles["heading"])]
		story.append(Paragraph(self._t("framework_desc"), self.styles["body"]))
		story.append(Spacer(1, 0.12 * inch))
		story.append(Paragraph(self._t("scoring_method"), self.styles["body"]))
		story.append(Spacer(1, 0.12 * inch))
		story.append(Paragraph(self._t("disclaimer"), self.styles["body"]))
		story.append(Spacer(1, 0.12 * inch))
		story.append(Paragraph(self._t("citation"), self.styles["body"]))
		return story

	def _build_exec_summary_story(
		self,
		company_profile: dict,
		scoring_result: ScoringResult,
		llm_analysis: FullAnalysis,
		radar_chart_bytes: bytes,
	) -> list[Any]:
		"""Build the executive summary page content."""

		story: list[Any] = [Paragraph(self._t("executive_summary"), self.styles["heading"])]
		story.append(Spacer(1, 0.05 * inch))
		story.append(self._build_maturity_badge(scoring_result))
		story.append(Spacer(1, 0.12 * inch))

		maturity_rows = [
			[Paragraph("EN", self.styles["table_header"]), Paragraph(scoring_result["maturity_label_en"], self.styles["table_body"])],
			[Paragraph("PT", self.styles["table_header"]), Paragraph(scoring_result["maturity_label_pt"], self.styles["table_body"])],
			[Paragraph("JA", self.styles["table_header"]), Paragraph(scoring_result["maturity_label_ja"], self.styles["table_body"])],
		]
		maturity_table = Table(maturity_rows, colWidths=[0.45 * inch, 2.7 * inch])
		maturity_table.setStyle(
			TableStyle(
				[
					("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F6F7F9")),
					("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D0D0D0")),
					("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
					("LEFTPADDING", (0, 0), (-1, -1), 4),
					("RIGHTPADDING", (0, 0), (-1, -1), 4),
					("TOPPADDING", (0, 0), (-1, -1), 5),
					("BOTTOMPADDING", (0, 0), (-1, -1), 5),
				]
			)
		)

		score_table = self._build_score_table(scoring_result)
		radar_image = self._build_radar_image(radar_chart_bytes)
		combined = Table(
			[[score_table, radar_image]],
			colWidths=[3.6 * inch, 3.2 * inch],
			style=TableStyle(
				[
					("VALIGN", (0, 0), (-1, -1), "TOP"),
					("LEFTPADDING", (0, 0), (-1, -1), 0),
					("RIGHTPADDING", (0, 0), (-1, -1), 0),
					("TOPPADDING", (0, 0), (-1, -1), 0),
					("BOTTOMPADDING", (0, 0), (-1, -1), 0),
				]
			),
		)

		story.append(maturity_table)
		exec_text = llm_analysis.get("executive_summary", "").strip()
		if exec_text:
			story.append(Spacer(1, 0.12 * inch))
			story.append(Paragraph(self._t("executive_summary"), self.styles["subheading"]))
			story.append(Paragraph(exec_text, self.styles["body"]))
			story.append(Spacer(1, 0.12 * inch))
		story.append(Spacer(1, 0.12 * inch))
		story.append(combined)
		return story

	def _build_benchmark_story(self, scoring_result: ScoringResult) -> list[Any]:
		"""Build the benchmark comparison page content."""

		story: list[Any] = [Paragraph(self._t("benchmark_comparison"), self.styles["heading"])]
		story.append(Spacer(1, 0.08 * inch))
		story.append(self._build_benchmark_drawing(scoring_result))
		story.append(Spacer(1, 0.12 * inch))
		story.append(Paragraph(self._benchmark_interpretation(scoring_result), self.styles["body"]))
		return story

	def _build_roadmap_story(self, scoring_result: ScoringResult, llm_analysis: FullAnalysis) -> list[Any]:
		"""Build the roadmap page content."""

		story: list[Any] = [Paragraph(self._t("roadmap"), self.styles["heading"])]
		story.append(Paragraph(self._t("top_actions"), self.styles["subheading"]))
		story.append(Spacer(1, 0.05 * inch))
		story.append(self._build_roadmap_table(scoring_result, llm_analysis))
		return story

	def _build_page(self, story: list[Any]) -> list[Any]:
		"""Wrap a story in a KeepInFrame so page layouts remain contained."""

		return [KeepInFrame(7.1 * inch, 9.45 * inch, story, mode="shrink")]

	def generate(
		self,
		company_profile: dict,
		scoring_result: ScoringResult,
		llm_analysis: FullAnalysis,
		radar_chart_bytes: bytes,
	) -> bytes:
		"""Generate the complete PDF report as bytes."""

		buffer = BytesIO()
		doc = SimpleDocTemplate(
			buffer,
			pagesize=A4,
			leftMargin=0.55 * inch,
			rightMargin=0.55 * inch,
			topMargin=0.6 * inch,
			bottomMargin=0.65 * inch,
			title="Digital Transformation Maturity Diagnostic Report",
			author="shinkyou_agent (診鏡 Shinkyō Agent)",
			subject="DX maturity diagnostic report",
		)

		story: list[Any] = []
		story.extend(self._build_cover_story(company_profile))
		story.append(PageBreak())
		story.extend(self._build_exec_summary_story(company_profile, scoring_result, llm_analysis, radar_chart_bytes))
		story.append(PageBreak())

		for dimension in DIMENSIONS:
			story.extend(self._build_page(self._build_dimension_story(dimension, scoring_result, llm_analysis)))
			story.append(PageBreak())

		story.extend(self._build_benchmark_story(scoring_result))
		story.append(PageBreak())
		story.extend(self._build_roadmap_story(scoring_result, llm_analysis))
		story.append(PageBreak())
		story.extend(self._build_methodology_story())

		doc.build(story, onFirstPage=self._page_footer, onLaterPages=self._page_footer)
		pdf_bytes = buffer.getvalue()
		buffer.close()
		return pdf_bytes
